federation_version: 2
subgraphs:
  products:
    routing_url: http://products:8080/graphql
    schema:
      subgraph_url: http://localhost:4001/graphql
  reviews:
    routing_url: http://reviews:8080/graphql
    schema:
      subgraph_url: http://localhost:4002/graphql
  search:
    routing_url: http://search:8080/graphql
    schema:
      subgraph_url: http://localhost:4003/graphql